version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=80
      - WORKERS=4
      - LOG_LEVEL=info
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Example with database (uncomment if needed)
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_DB=mydatabase
  #     - POSTGRES_USER=myuser
  #     - POSTGRES_PASSWORD=mypassword
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: